language: cpp
matrix:
  include:
  - os: osx
    before_script: brew install glslang
    env: VALIDATOR="glslangValidator"
  - os: linux
    dist: trusty
    sudo: false
    before_script:
    - curl https://cvs.khronos.org/svn/repos/ogl/trunk/ecosystem/public/sdk/tools/glslang/Install/Linux/glslangValidator --output glslangValidator
    - chmod +x glslangValidator
    env: VALIDATOR="./glslangValidator"
script:
- ${VALIDATOR} -v
- find shaders -name "*.frag" -or -name "*.vert" | xargs ${VALIDATOR}
